name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publish Docker
        uses: sergeysova/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: authmenow/frontend/frontend
          username: sergeysova
          password: ${{ secrets.GITHUB_TOKEN }}
          snapshot: true
          tags: latest
          tag_names: true
          tag_semver: true

      - name: Trigger deploy to Dev
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_DEPLOY_TOKEN }}
          repository: authmenow/releases
          event-type: deploy-dev
